# gitops/config.py
# Конфигурация для GitOps интеграции с GitHub/GitLab

from pydantic_settings import BaseSettings, SettingsConfigDict


class GitOpsSettings(BaseSettings):
    """Настройки для GitOps PR bot."""

    model_config = SettingsConfigDict(
        env_prefix="GITOPS_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Provider: "github" или "gitlab"
    provider: str = "github"

    # API credentials
    token: str = ""
    api_url: str = "https://api.github.com"  # или "https://gitlab.com/api/v4"

    # Repository settings
    repo_owner: str = ""  # GitHub: owner, GitLab: namespace
    repo_name: str = ""   # Repository name
    base_branch: str = "main"

    # PR settings
    branch_prefix: str = "secureguard-policy-"
    pr_title_template: str = "feat: Add NetworkPolicy {policy_id}"
    pr_body_template: str = """## NetworkPolicy Suggestion

**Policy ID:** {policy_id}
**Severity:** {severity}
**Risk Score:** {risk_score}

### Reason
{reason}

### Source → Destination
{source} → {destination}

---
*Generated by SecureGuard Drift*
"""

    # File path in repo where policies should be committed
    policies_path: str = "kubernetes/network-policies"

    # Enabled flag
    enabled: bool = False


# Global settings instance
settings = GitOpsSettings()


if __name__ == "__main__":
    print("GitOps Settings:")
    print(f"  Provider: {settings.provider}")
    print(f"  Enabled: {settings.enabled}")
    print(f"  Repo: {settings.repo_owner}/{settings.repo_name}")
    print(f"  Base Branch: {settings.base_branch}")
